<a href="https://colab.research.google.com/github/NileshPatil24-a/Complete_DataScience_Revision/blob/main/numpy_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
array = np.array([12,3,4])

In [6]:
array

array([12,  3,  4])

In [9]:
TwoDArray = np.array([[1,2,3],[3,4,5],[4,5,6]])

In [10]:
print(TwoDArray)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [15]:
array1  = np.arange(1,11,2)
print(np.arange(1,11))
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [23]:
print(np.zeros((4,5)))
print(np.ones((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
print(np.linspace(1,10,100))
# all have same linear space

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [40]:
print(np.random.rand(6))
# normalizartion 0 to 1

print(np.random.randn(5))
# stadardization -3 to 3

print(np.random.randint(1,10,6))

[0.80572564 0.63350771 0.59472089 0.80014747 0.2003356  0.96083699]
[ 1.27903932  1.46349963 -0.38513256  0.78196623 -0.33854855]
[1 7 6 2 9 5]


In [50]:
arr = np.arange(1,17)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [52]:
arr = arr.reshape(4,4)

In [53]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [59]:
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.max())
print(arr.min())
print(arr.std())
print(arr.mean())
print(arr.argmax())
print(arr.argmin())

(4, 4)
16
int64
16
1
4.6097722286464435
8.5
15
0


In [68]:
arr = np.arange(1,10)
print(arr)
print(arr[3:6])
print(arr[2: :2])

[1 2 3 4 5 6 7 8 9]
[4 5 6]
[3 5 7 9]
